# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'self-hosted-pool'

steps:

- script: |
    python3 -m pip install --upgrade pip
    python3 install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    export PYTHONPATH=$PYTHONPATH:.
    pytest
  displayName: 'Run Tests'
