# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'self-hosted-pool'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.14'
  displayName: 'Setup Python'

- script: |
    python -m pip install --upgrade pip
    python install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    export PYTHONPATH=$PYTHONPATH:.
    pytest
  displayName: 'Run Tests'
